---
title: "2.0 Combine Models"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{ModelCombine}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Setup Libraries
```{r setup}
library(tswgewrapped)
```

# Load Data
```{r}
# Load Data
file = system.file("extdata", "USeconomic.csv", package = "tswgewrapped", mustWork = TRUE)
USeconomic = read.csv(file, header = TRUE, stringsAsFactors = FALSE, check.names = FALSE)
names(USeconomic) = gsub("[(|)]", "", colnames(USeconomic))
data = USeconomic
```

# Model Global Settings
```{r}
var_interest = 'logGNP'
batch_size = 132
n.ahead = 2
```

# 1.0 Build and Compare Models

## 1.1 Univariate
```{r}
models = list("Univar A" = list(phi = 0.9, d = 1, s = 0, sliding_ase = TRUE),
              "Univar B" = list(phi = 0.9, d = 1, s = 4, sliding_ase = TRUE),
              "Univar C" = list(phi = 0.9, d = 1, s = 4, sliding_ase = FALSE)
              )

mdl_compare_uni = ModelCompareUnivariate$new(data = data, var_interest = var_interest, mdl_list = models,
                                             n.ahead = n.ahead, batch_size = batch_size)

```

## 1.2 VAR
```{r}
lag.max = 10

models = list("AIC None" = list(select = "aic", trend_type = "none", lag.max = lag.max),
              "AIC Trend" = list(select = "aic", trend_type = "trend", lag.max = lag.max),
              "AIC Both" = list(select = "aic", trend_type = "both", lag.max = lag.max))


mdl_build_var = ModelBuildMultivariateVAR$new(data = data, var_interest = var_interest,
                                              mdl_list = models, verbose = 0)

mdl_build_var$build_recommended_models()
models = mdl_build_var$get_final_models(subset = 'r')

# Setup Models to be compared with sliding ASE = TRUE
for (name in names(models)){
  models[[name]][['sliding_ase']] = TRUE
}

# Initialize the ModelCompareMultivariateVAR object
mdl_compare_var = ModelCompareMultivariateVAR$new(data = data, var_interest = var_interest,
                                                  mdl_list = models, n.ahead = n.ahead, batch_size = batch_size, verbose = 0)

```

## 1.3 NNFOR::mlp() Caret ####

**Since this process takes some time, I have commented this out for now and saved an already created caret model. However, feel free to uncomment this and run the model build process.**

```{r}
# library(caret)
# 
# # Random Parallel
# model = ModelBuildNNforCaret$new(data = data, var_interest = "logGNP", m = 2,
#                                  search = 'random',
#                                  grid = NA, tuneLength = 2,
#                                  batch_size = 132, h = 2,
#                                  parallel = TRUE,
#                                  seed = 1,
#                                  verbose = 1)
# 
# model$summarize_hyperparam_results()
# caret_model = model$get_final_models(subset = 'a')

file = system.file("extdata", "caret_model_batch_ase.rds", package = "tswgewrapped", mustWork = TRUE)
caret_model = readRDS(file)

# Initialize the ModelCompareMultivariateVAR object
mdl_compare_mlp = ModelCompareNNforCaret$new(data = data, var_interest = var_interest,
                                             mdl_list = caret_model,
                                             verbose = 1)
```

# 2.0 Combine all models

```{r}
mdl_combine = ModelCombine$new(data = data, var_interest = "logGNP",
                               uni_models = mdl_compare_uni, var_models = mdl_compare_var, mlp_models = mdl_compare_mlp,
                               verbose = 1)
```

## Statistical Comparison
```{r}
mdl_combine$plot_boxplot_ases()
```

```{r}
comparison = mdl_combine$statistical_compare()
```

## ASEs
```{r}
ases = mdl_combine$get_tabular_metrics()
ases
```

```{r fig.width=12, fig.height=6}
mdl_combine$plot_batch_ases()
```

## Forecasts
```{r}
forecasts = mdl_combine$get_tabular_metrics(ases = FALSE)
forecasts
```

```{r fig.width=12, fig.height=6}
mdl_combine$plot_batch_forecasts()
```

